version: "3.3"

services:
  mongo:
    image: mongo
    volumes:
      - data:/opt/mongodb/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: lectrum
      MONGO_INITDB_ROOT_PASSWORD: lectrum
      MONGO_INITDB_DATABASE: lectrum
    ports:
      - 27017:27017
  minio:
    image: quay.io/minio/minio:RELEASE.2021-11-24T23-19-33Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - data:/data
    ports:
      - 9000:9000
      - 9001:9001

volumes:
  data: {}